### PR TITLE
Drop machine dependant code in makefiles

### PR DESCRIPTION
**Pull request by Herrie82**
As per
https://github.com/webosose/cmake-modules-webos/commit/82f4f25baedfed2ba33c7ee707f898f18da44b19

### CODE REVIEW

**Comment by Tofee** [comment]
Maybe we could make it really machine independant, and have common build flags whatever the target?

**Comment by Herrie82** [comment]
> Maybe we could make it really machine independant, and have common build flags whatever the target?

To be honest I have no idea why this is here and what it does....

**Comment by Tofee** [comment]
> > Maybe we could make it really machine independant, and have common build flags whatever the target?
> 
> To be honest I have no idea why this is here and what it does....

Same here. I guess it's an old issue with an old compiler, so it's worth a try to just remove this couple lines of code

**Comment by Herrie82** [comment]
> > > Maybe we could make it really machine independant, and have common build flags whatever the target?
> > 
> > 
> > To be honest I have no idea why this is here and what it does....
> 
> Same here. I guess it's an old issue with an old compiler, so it's worth a try to just remove this couple lines of code

Seems to build OK for qemux86-64, so removed the flags completely.

**Pull request merged**
